### ISSUE TITLE
igshid is only found on instagram

### ISSUE THREAD

**Issue by arthuredelstein** [privacytests/privacytests.org#146]
Browsers that are scoping igshid to instagram.com would be unfairly penalized. I should potentially go through the list of query parameters and see which are best to include.

**Comment by alfredonodo** [comment]
Hi,
can you look at [this](https://github.com/brave/brave-browser/issues/11580#issuecomment-1456859781)?
Thank you

**Comment by arthuredelstein** [comment]
Hi @alfredonodo -- thanks. I have confirmed this isn't needed and removed `igshid` from the set of tested parameters in f26d12cc847b947c6beae749cdb92bedd24afd5e. The parameter will be removed in the next published issue.

**Comment by alfredonodo** [comment]
Hi,
the igshid parameter is still present.
Thank you

**Comment by arthuredelstein** [comment]
Thanks! This was due to a problem with a test server updating code and has
now been fixed.
