### ISSUE TITLE
Vanadium browser

### ISSUE THREAD

**Issue by w9925** [privacytests/privacytests.org#147]
Please add the Vanadium browser by GrapheneOS

**Comment by Thorin-Oakenpants** [comment]
duplicate of https://github.com/arthuredelstein/privacytests.org/issues/66#issuecomment-1012531114

**Comment by inson1** [comment]
Why it isnt closed if its duplicate?

**Comment by arthuredelstein** [comment]
Hi @w9925 -- I'm currently not adding browsers, but Vanadium is high on my list for the future. Please see #66.
