### ISSUE TITLE
help with librewolf and turning off blob?

### ISSUE THREAD

**Issue by HellyTubbies** [privacytests/privacytests.org#155]
is it possible? im not sure which setting to search on librewolf to turn it off.

**Comment by arthuredelstein** [comment]
`privacy.partition.bloburl_per_agent_cluster` sort of works. However it seems to also block legitimate blob use, so I don't fully understand the consequences.

**Comment by HellyTubbies** [comment]
> `privacy.partition.bloburl_per_agent_cluster` sort of works. However it seems to also block legitimate blob use, so I don't fully understand the consequences.

alright. will try it out.
