### ISSUE TITLE
HTTPS test result Brave Browser

### ISSUE THREAD

**Issue by 1270011** [privacytests/privacytests.org#157]
The features of HTTPS in the browser testing section in brave are apparently not correct. Brave supports https on all sites, which is realized through the integrated Brave shields. This integration is based on https everywhere.
Here are the related links:
1. https://support.brave.com/hc/en-us/articles/360022806212-How-do-I-use-Shields-while-browsing-
2. https://www.eff.org/https-everywhere

However, it is possible that the user have to manually activate the feature. If you like, I could test it if it is enabled by default or not after a clean install of brave.
The correspondig setting can be found in: 

brave://settings/security

I would be very pleased about feedback and the further procedure. Thank you!

**Comment by arthuredelstein** [comment]
Thanks for keeping an eye on this @1270011! Indeed @Thorin-Oakenpants is right that Brave is currently rolling out the HTTPS by Default feature in 1.50. You can see all but the "insecure website" test passes in Brave Nightly 1.51: https://privacytests.org/nightly.html

**Comment by Thorin-Oakenpants** [comment]
... aaaaaaaand ... issue 52 shows it failed (desktop says 1.50, shows upgradable address/hyperlinks as X) - did the feaure miss the boat?

**Comment by arthuredelstein** [comment]
@Thorin-Oakenpants -- no, it's rolling out gradually. Currently at 15% of clients.

**Comment by alfredonodo** [comment]
> @Thorin-Oakenpants -- no, it's rolling out gradually. Currently at 15% of clients.

Is there a resource where you can find the progress status?

**Comment by arthuredelstein** [comment]
> > @Thorin-Oakenpants -- no, it's rolling out gradually. Currently at 15% of clients.
> 
> Is there a resource where you can find the progress status?

You can follow this file: https://github.com/brave/brave-variations/blob/production/seed/seed.json#L1889. It currently indicates that the HttpsByDefault feature is at 15% in Release for Desktop and Android.
