### ISSUE TITLE
Add duckduckgo browser (macOS)

### ISSUE THREAD

**Issue by miguelslp** [privacytests/privacytests.org#159]
Hi, could you please consider adding duckduckgo browser (currently, macOS only) ? Curious how it differs from Safari. Thanks!

**Comment by arthuredelstein** [comment]
Hi! DuckDuckGo desktop browser for Mac is still in Beta, so I am currently publishing its test results in https://privacytests.org/nightly.html. Once it's available in Release I will add it to the main desktop page.

**Comment by miguelslp** [comment]
Thanks!
