### ISSUE TITLE
Fingerprinting resistance tests

### ISSUE THREAD

**Issue by alfredonodo** [privacytests/privacytests.org#162]
Hi,
why does brave pass only one test in fingerprinting protection despite having many countermeasures such as [fingerprint randomisztion](https://brave.com/privacy-updates/3-fingerprint-randomization/), [fingerprinting defenses 2.0](https://brave.com/privacy-updates/4-fingerprinting-defenses-2.0/), [protecting against browser-language fingerprinting](https://brave.com/privacy-updates/17-language-fingerprinting/), [preventing SpeechSynthesis-Based Browser Fingerprinting](https://brave.com/privacy-updates/15-grab-bag-3/)?

**Comment by arthuredelstein** [comment]
Thanks for the good question. Currently, the set of fingerprinting tests in PrivacyTests is very limited. I hope to rectify this in the coming months. That will hopefully bring a more complete view of the state of fingerprinting protections in browsers.

However, it might be of interest that Brave Nightly is providing more fingerprinting protections. These are in the process of being rolled out. See for example: https://privacytests.org/archive/issue53/nightly.html
