### ISSUE TITLE
Is it possible to use your server resources for private testing?

### ISSUE THREAD

**Issue by uazo** [privacytests/privacytests.org#170]
hi @arthuredelstein 

I occasionally use your repo to check some implementations I do, mainly as a non-regression test.
since non-public server resources are being used to run your tests, I would like to ask you if it is possible to have server-side code available as well, or if alternatively it is okay to use your own server resources.

thank you for your work

**Comment by uazo** [comment]
> You are very welcome to use my server when you run the tests

thank you very much! for me it is much simpler that way!

>  You can see it in the live/ and static/ directories

sorry, I didn't realise

**Comment by arthuredelstein** [comment]
No problem @uazo! Thank you for using it. :)
