### ISSUE TITLE
feature request: can you addy cachybrowser?

### ISSUE THREAD

**Issue by zombiehoffa** [privacytests/privacytests.org#189]
Hi, would it be possible to add cachy browser? https://github.com/CachyOS/CachyOS-Browser-Settings

aur package here: https://aur.archlinux.org/packages/cachy-browser

bonus bonus request: would be interesting to see mercury browser too: https://thorium.rocks/mercury

**Comment by arthuredelstein** [comment]
Hi -- thank you for the suggestion. I'm currently focused on adding more tests, but I will add your suggestions to our list on issue #66.

**Comment by inson1** [comment]
@arthuredelstein btw you could also close #147

**Comment by inson1** [comment]
@arthuredelstein I updated it and I think found all these issues (or almost all)

**Comment by Tuscann** [comment]
Can you add Floorp and Thorium browsers?

**Comment by inson1** [comment]
@Tuscann 
bad issue - #66 is the right issue
thorium is already in the list for new browsers
