### ISSUE TITLE
Add Floorp browser?

### ISSUE THREAD

**Issue by Mr-Bajs** [privacytests/privacytests.org#201]
Floorp browser is a firefox fork mostly changes to the UI. Could be viewed as a firefox version of vivaldi. I just recently found out about it. I'll guess it's been trending in the internet. It would be intressting how well it compares to other browsers in these tests.

Atleast consider adding floorp.

https://floorp.app/en/
https://github.com/Floorp-Projects

**Comment by Yellow224** [comment]
put this in pull requests

**Comment by inson1** [comment]
@Mr-Bajs bad issue - https://github.com/privacytests/privacytests.org/issues/66 is the right issue
someone already written aot Floorp in that issue
