### ISSUE TITLE
Misc tests: eTLD+1 window.name clearance

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [privacytests/privacytests.org#71]
https://arkenfox.github.io/TZP/tests/windownamea.html

**Comment by Thorin-Oakenpants** [comment]
thanks @arthuredelstein - https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40720#note_2761872

**Comment by arthuredelstein** [comment]
Thank you @Thorin-Oakenpants !
